### ISSUE TITLE
Local reference table overflow on Android API levels 23-25

### ISSUE THREAD

**Issue by mhsmith** [beeware/rubicon-java#74]
**Describe the bug**

As noted at https://github.com/beeware/briefcase/issues/538, BeeWare doesn't work on Android API level 22 or older. But I've found that the app on [page 2 of the tutorial](https://docs.beeware.org/en/latest/tutorial/tutorial-2.html#adding-some-content-of-our-own) also crashes on some newer Android versions.

The crash happens with the x86_64 emulator on API levels 23 and 25, but not on levels 26, 27 or 31. I don't know if it also affects physical devices, because I don't have one in the level 23-25 range.

I've reduced it to the following minimal example. Either the label or the button alone works fine: the crash only happens if I include both of them. Two labels is also fine.

```python
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW

class HelloWorld(toga.App):

    def startup(self):
        main_box = toga.Box()

        label = toga.Label("Hello world")
        main_box.add(label)

        button = toga.Button("Hello world")
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

def main():
    return HelloWorld()
```

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.8
 - Software versions:
   - Briefcase: 0.3.7
   - Toga: 0.3.0.dev34
   - rubicon-java: 0.2.6

**Log from API level 25:**
```
D/MainActivity: Python.run() start
D/Python: Running 'helloworld' as __main__...
W/mple.helloworld: type=1400 audit(0.0:15): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
I/Python: Python app launched & stored in Android Activity class
A/art: art/runtime/indirect_reference_table.cc:132] JNI ERROR (app bug): local reference table overflow (max=512)
A/art: art/runtime/indirect_reference_table.cc:132] local reference table dump:
A/art: art/runtime/indirect_reference_table.cc:132]   Last 10 entries (of 512):
A/art: art/runtime/indirect_reference_table.cc:132]       511: 0x70ff5510 java.lang.String "int"
A/art: art/runtime/indirect_reference_table.cc:132]       510: 0x70f5cd68 java.lang.Class<int>
A/art: art/runtime/indirect_reference_table.cc:132]       509: 0x12d5e870 java.lang.Class[] (1 elements)
A/art: art/runtime/indirect_reference_table.cc:132]       508: 0x12d02100 java.lang.reflect.Method
A/art: art/runtime/indirect_reference_table.cc:132]       507: 0x12d5e8a0 java.lang.reflect.Method[] (1 elements)
A/art: art/runtime/indirect_reference_table.cc:132]       506: 0x12c4f480 java.lang.String "getDimensionPixe... (21 chars)
A/art: art/runtime/indirect_reference_table.cc:132]       505: 0x12c4f440 java.lang.String "getDimensionPixe... (21 chars)
A/art: art/runtime/indirect_reference_table.cc:132]       504: 0x12c09e98 android.content.res.Resources
A/art: art/runtime/indirect_reference_table.cc:132]       503: 0x12c42230 org.beeware.android.MainActivity
A/art: art/runtime/indirect_reference_table.cc:132]       502: 0x12d0e6e0 java.lang.String "android"
A/art: art/runtime/indirect_reference_table.cc:132]   Summary:
A/art: art/runtime/indirect_reference_table.cc:132]         1 of $Proxy1
A/art: art/runtime/indirect_reference_table.cc:132]         1 of $Proxy2
A/art: art/runtime/indirect_reference_table.cc:132]         1 of $Proxy0
A/art: art/runtime/indirect_reference_table.cc:132]        10 of org.beeware.android.MainActivity (1 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         1 of java.io.FileDescriptor
A/art: art/runtime/indirect_reference_table.cc:132]        79 of java.lang.reflect.Method (79 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]       172 of java.lang.String (133 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]       112 of java.lang.Class (89 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]        15 of java.lang.Class[] (1 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]        27 of java.lang.Class[] (1 elements) (27 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]        14 of java.lang.Class[] (2 elements) (14 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]        12 of java.lang.Class[] (3 elements) (12 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]        11 of java.lang.Class[] (4 elements) (11 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]        26 of java.lang.reflect.Method[] (1 elements) (26 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         2 of java.lang.reflect.Method[] (2 elements) (2 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         5 of java.lang.reflect.Method[] (3 elements) (5 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         2 of java.lang.reflect.Method[] (6 elements) (2 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         1 of java.lang.reflect.Method[] (22 elements)
A/art: art/runtime/indirect_reference_table.cc:132]         1 of java.lang.String[] (4 elements)
A/art: art/runtime/indirect_reference_table.cc:132]         3 of android.util.DisplayMetrics (1 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         1 of android.graphics.Typeface
A/art: art/runtime/indirect_reference_table.cc:132]         1 of android.widget.TextView
A/art: art/runtime/indirect_reference_table.cc:132]         3 of android.view.View (3 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         5 of android.content.res.Resources (1 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]         1 of android.os.Looper
A/art: art/runtime/indirect_reference_table.cc:132]         1 of android.widget.Button
A/art: art/runtime/indirect_reference_table.cc:132]         1 of android.os.MessageQueue
A/art: art/runtime/indirect_reference_table.cc:132]         1 of android.widget.RelativeLayout
A/art: art/runtime/indirect_reference_table.cc:132]         2 of android.widget.RelativeLayout$LayoutParams (2 unique instances)
A/art: art/runtime/indirect_reference_table.cc:132]
A/art: art/runtime/runtime.cc:422] Runtime aborting...
A/art: art/runtime/runtime.cc:422] Aborting thread:
A/art: art/runtime/runtime.cc:422] "main" prio=10 tid=1 Runnable
A/art: art/runtime/runtime.cc:422]   | group="" sCount=0 dsCount=0 obj=0x7612b260 self=0x7b50da695a00
A/art: art/runtime/runtime.cc:422]   | sysTid=3303 nice=-10 cgrp=default sched=0/0 handle=0x7b50df011b40
A/art: art/runtime/runtime.cc:422]   | state=R schedstat=( 0 0 0 ) utm=735 stm=126 core=3 HZ=100
A/art: art/runtime/runtime.cc:422]   | stack=0x7fff22df3000-0x7fff22df5000 stackSize=8MB
A/art: art/runtime/runtime.cc:422]   | held mutexes= "abort lock" "mutator lock"(shared held)
A/art: art/runtime/runtime.cc:422]   native: #00 pc 0000000000531a6e  /system/lib64/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+238)
A/art: art/runtime/runtime.cc:422]   native: #01 pc 000000000050278c  /system/lib64/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+412)
A/art: art/runtime/runtime.cc:422]   native: #02 pc 00000000004ef4cb  /system/lib64/libart.so (_ZNK3art10AbortState10DumpThreadERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEPNS_6ThreadE+43)
A/art: art/runtime/runtime.cc:422]   native: #03 pc 00000000004ef232  /system/lib64/libart.so (_ZNK3art10AbortState4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+274)
A/art: art/runtime/runtime.cc:422]   native: #04 pc 00000000004e2000  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+128)
A/art: art/runtime/runtime.cc:422]   native: #05 pc 000000000014ceae  /system/lib64/libart.so (_ZN3art10LogMessageD1Ev+1630)
A/art: art/runtime/runtime.cc:422]   native: #06 pc 00000000002cd310  /system/lib64/libart.so (_ZN3art22IndirectReferenceTable3AddEjPNS_6mirror6ObjectE+304)
A/art: art/runtime/runtime.cc:422]   native: #07 pc 00000000003e29c0  /system/lib64/libart.so (_ZN3art3JNI21GetObjectArrayElementEP7_JNIEnvP13_jobjectArrayi+832)
A/art: art/runtime/runtime.cc:422]   native: #08 pc 0000000000162e8b  /system/lib64/libart.so (_ZN3art8CheckJNI21GetObjectArrayElementEP7_JNIEnvP13_jobjectArrayi+843)
A/art: art/runtime/runtime.cc:422]   native: #09 pc 000000000000a43c  /data/app/com.example.helloworld-1/lib/x86_64/libffi.so (???)
A/art: art/runtime/runtime.cc:422]   native: #10 pc 000000000000977d  /data/app/com.example.helloworld-1/lib/x86_64/libffi.so (???)
A/art: art/runtime/runtime.cc:422]   native: #11 pc 0000000000009315  /data/app/com.example.helloworld-1/lib/x86_64/libffi.so (ffi_call+101)
A/art: art/runtime/runtime.cc:422]   native: #12 pc 00000000000157bb  /data/data/com.example.helloworld/files/python/stdlib/lib/python3.8/lib-dynload/_ctypes.cpython-38.so (_call_function_pointer+331)
A/art: art/runtime/runtime.cc:422]   native: #13 pc 000000000001521f  /data/data/com.example.helloworld/files/python/stdlib/lib/python3.8/lib-dynload/_ctypes.cpython-38.so (_ctypes_callproc+1119)
A/art: art/runtime/runtime.cc:422]   native: #14 pc 000000000000a931  /data/data/com.example.helloworld/files/python/stdlib/lib/python3.8/lib-dynload/_ctypes.cpython-38.so (PyCFuncPtr_call+737)
A/art: art/runtime/runtime.cc:422]   native: #15 pc 0000000000098ea2  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyObject_MakeTpCall+450)
A/art: art/runtime/runtime.cc:422]   native: #16 pc 00000000001c8701  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #17 pc 00000000001c60b3  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #18 pc 00000000001c2cf4  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyEval_EvalFrameDefault+26452)
A/art: art/runtime/runtime.cc:422]   native: #19 pc 00000000001bc596  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyEval_EvalFrameEx+86)
A/art: art/runtime/runtime.cc:422]   native: #20 pc 0000000000099edb  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #21 pc 000000000009a0c9  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyFunction_Vectorcall+249)
A/art: art/runtime/runtime.cc:422]   native: #22 pc 00000000001c8720  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #23 pc 00000000001c60b3  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #24 pc 00000000001c2d9f  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyEval_EvalFrameDefault+26623)
A/art: art/runtime/runtime.cc:422]   native: #25 pc 00000000001bc596  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyEval_EvalFrameEx+86)
A/art: art/runtime/runtime.cc:422]   native: #26 pc 0000000000099edb  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #27 pc 000000000009a0c9  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyFunction_Vectorcall+249)
A/art: art/runtime/runtime.cc:422]   native: #28 pc 00000000001c8720  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #29 pc 00000000001c60b3  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #30 pc 00000000001c2d9f  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyEval_EvalFrameDefault+26623)
A/art: art/runtime/runtime.cc:422]   native: #31 pc 00000000001bc596  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyEval_EvalFrameEx+86)
A/art: art/runtime/runtime.cc:422]   native: #32 pc 0000000000099edb  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #33 pc 000000000009a0c9  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyFunction_Vectorcall+249)
A/art: art/runtime/runtime.cc:422]   native: #34 pc 00000000001c8720  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #35 pc 00000000001c60b3  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #36 pc 00000000001c2d9f  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyEval_EvalFrameDefault+26623)
A/art: art/runtime/runtime.cc:422]   native: #37 pc 00000000001bc596  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyEval_EvalFrameEx+86)
A/art: art/runtime/runtime.cc:422]   native: #38 pc 0000000000099edb  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #39 pc 000000000009a0c9  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyFunction_Vectorcall+249)
A/art: art/runtime/runtime.cc:422]   native: #40 pc 000000000009f0d0  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #41 pc 000000000009e17d  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #42 pc 000000000009cac0  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #43 pc 000000000009aff8  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #44 pc 000000000009c5d5  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #45 pc 000000000009c9ba  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyObject_CallFunctionObjArgs+346)
A/art: art/runtime/runtime.cc:422]   native: #46 pc 000000000011beee  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #47 pc 00000000001178a6  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #48 pc 00000000000f8fc7  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyObject_GetAttr+151)
A/art: art/runtime/runtime.cc:422]   native: #49 pc 00000000000f9da6  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyObject_GetMethod+118)
A/art: art/runtime/runtime.cc:422]   native: #50 pc 00000000001c2c12  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyEval_EvalFrameDefault+26226)
A/art: art/runtime/runtime.cc:422]   native: #51 pc 00000000001bc596  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyEval_EvalFrameEx+86)
A/art: art/runtime/runtime.cc:422]   native: #52 pc 0000000000099edb  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #53 pc 000000000009a0c9  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyFunction_Vectorcall+249)
A/art: art/runtime/runtime.cc:422]   native: #54 pc 00000000001c8720  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #55 pc 00000000001c60b3  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #56 pc 00000000001c2d34  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyEval_EvalFrameDefault+26516)
A/art: art/runtime/runtime.cc:422]   native: #57 pc 00000000001bc596  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (PyEval_EvalFrameEx+86)
A/art: art/runtime/runtime.cc:422]   native: #58 pc 0000000000099edb  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #59 pc 000000000009a0c9  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyFunction_Vectorcall+249)
A/art: art/runtime/runtime.cc:422]   native: #60 pc 00000000000a99a0  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #61 pc 00000000000a9928  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #62 pc 00000000000a82cd  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (???)
A/art: art/runtime/runtime.cc:422]   native: #63 pc 00000000000f998b  /data/app/com.example.helloworld-1/lib/x86_64/libpython3.8.so (_PyObject_GenericGetAttrWithDict+315)
A/art: art/runtime/runtime.cc:422]   at org.beeware.rubicon.Python.run(Native method)
A/art: art/runtime/runtime.cc:422]   at org.beeware.android.MainActivity.startPython(MainActivity.java:231)
A/art: art/runtime/runtime.cc:422]   at org.beeware.android.MainActivity.onCreate(MainActivity.java:248)
A/art: art/runtime/runtime.cc:422]   at android.app.Activity.performCreate(Activity.java:6679)
A/art: art/runtime/runtime.cc:422]   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.-wrap12(ActivityThread.java:-1)
A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
A/art: art/runtime/runtime.cc:422]   at android.os.Handler.dispatchMessage(Handler.java:102)
A/art: art/runtime/runtime.cc:422]   at android.os.Looper.loop(Looper.java:154)
A/art: art/runtime/runtime.cc:422]   at android.app.ActivityThread.main(ActivityThread.java:6119)
A/art: art/runtime/runtime.cc:422]   at java.lang.reflect.Method.invoke!(Native method)
A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
A/art: art/runtime/runtime.cc:422]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by mhsmith** [comment]
According to the Android Studio new project wizard, about 11% of users are on API level 25 or older, compared to only 2% on level 22 or older. 

If we decide to stop supporting older Android versions, then the `minSdkVersion` in the template (currently set to 21) should be increased to prevent apps from being installed on unsupported devices. It's better for an app to refuse to install, than it is for it to install, display the BeeWare logo for a few seconds, and then crash.

**Comment by freakboy3742** [comment]
Interesting - I was under the impression that the size of the local reference table was kernel dependent (and thus highly device dependent). @mhsmith Are you able to shed any more light on this?

Ironically, this limit was the reason that BeeWare originally avoided the JNI/ctypes/CPython bridging approach (this was back in the "Android 4.4 is the new hotness" era). At the time, we ended up using a size-bound LRU cache for JNI local references, which... worked... but meant that any device with a small local reference limit ended up hitting this cache pretty hard, which caused a *huge* slow down.

Completely agreed that it's better to refuse install than to install and crash; a minimum version bump seems completely appropriate as an approach. Excluding 11% of users with this decision is a *little* higher than I'd like, but not fundamentally unreasonable; although I'd feel a lot better if we could point at a clear "You device isn't supported by the manufacturer, so we won't support it either". Wikipedia suggests 7.X support was stopped in 2019, but I can't find an official source for that; and it's not entirely clear to me what this would mean in the context of the Android ecosystem, since there is (as I understand it) a difference between "Google/Android support" and "your device manufacturer enables that support". 

In terms of implementation - is it *just* the `minSdkVersion` in the app template? Or do we need to rebuild the support libraries (and Rubicon) as well?

**Comment by freakboy3742** [comment]
Ok - thanks for that analysis. On that basis, the combination of (admittedly fuzzy) official OS support, in-practice version usage, and the removal of the reference limit suggests minSdkVersion=26 is a reasonable minimum to enforce. 

This would mean the oldest Google devices that are supported are the Nexus 5X and 6P, both of which are 6 years old; we support Apple devices that are 8 years old, so we're at least in the same ballpark in terms of longevity of device support.
